//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingDbTestApp.PingServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PingServiceReference.IPingService")]
    public interface IPingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPingService/IsDbUp", ReplyAction="http://tempuri.org/IPingService/IsDbUpResponse")]
        bool IsDbUp(string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPingService/IsDbUp", ReplyAction="http://tempuri.org/IPingService/IsDbUpResponse")]
        System.Threading.Tasks.Task<bool> IsDbUpAsync(string connectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPingServiceChannel : PingDbTestApp.PingServiceReference.IPingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PingServiceClient : System.ServiceModel.ClientBase<PingDbTestApp.PingServiceReference.IPingService>, PingDbTestApp.PingServiceReference.IPingService {
        
        public PingServiceClient() {
        }
        
        public PingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsDbUp(string connectionString) {
            return base.Channel.IsDbUp(connectionString);
        }
        
        public System.Threading.Tasks.Task<bool> IsDbUpAsync(string connectionString) {
            return base.Channel.IsDbUpAsync(connectionString);
        }
    }
}
