//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TwoTableJoin
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CookBookEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CookBookEntities object using the connection string found in the 'CookBookEntities' section of the application configuration file.
        /// </summary>
        public CookBookEntities() : base("name=CookBookEntities", "CookBookEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CookBookEntities object.
        /// </summary>
        public CookBookEntities(string connectionString) : base(connectionString, "CookBookEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CookBookEntities object.
        /// </summary>
        public CookBookEntities(EntityConnection connection) : base(connection, "CookBookEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Files> Files
        {
            get
            {
                if ((_Files == null))
                {
                    _Files = base.CreateObjectSet<Files>("Files");
                }
                return _Files;
            }
        }
        private ObjectSet<Files> _Files;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Files EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFiles(Files files)
        {
            base.AddObject("Files", files);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<GetUsers_Result> GetUsers()
        {
            return base.ExecuteFunction<GetUsers_Result>("GetUsers");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="vFileName">No Metadata Documentation available.</param>
        public ObjectResult<ReadFile_Result> ReadFile(global::System.String vFileName)
        {
            ObjectParameter vFileNameParameter;
            if (vFileName != null)
            {
                vFileNameParameter = new ObjectParameter("vFileName", vFileName);
            }
            else
            {
                vFileNameParameter = new ObjectParameter("vFileName", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<ReadFile_Result>("ReadFile", vFileNameParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="vFileName">No Metadata Documentation available.</param>
        /// <param name="vFile">No Metadata Documentation available.</param>
        public int SaveFile(global::System.String vFileName, global::System.Byte[] vFile)
        {
            ObjectParameter vFileNameParameter;
            if (vFileName != null)
            {
                vFileNameParameter = new ObjectParameter("vFileName", vFileName);
            }
            else
            {
                vFileNameParameter = new ObjectParameter("vFileName", typeof(global::System.String));
            }
    
            ObjectParameter vFileParameter;
            if (vFile != null)
            {
                vFileParameter = new ObjectParameter("vFile", vFile);
            }
            else
            {
                vFileParameter = new ObjectParameter("vFile", typeof(global::System.Byte[]));
            }
    
            return base.ExecuteFunction("SaveFile", vFileNameParameter, vFileParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CookBookModel", Name="Files")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Files : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Files object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="file_name">Initial value of the File_name property.</param>
        /// <param name="file_content">Initial value of the File_content property.</param>
        public static Files CreateFiles(global::System.Byte id, global::System.String file_name, global::System.Byte[] file_content)
        {
            Files files = new Files();
            files.ID = id;
            files.File_name = file_name;
            files.File_content = file_content;
            return files;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Byte _ID;
        partial void OnIDChanging(global::System.Byte value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String File_name
        {
            get
            {
                return _File_name;
            }
            set
            {
                OnFile_nameChanging(value);
                ReportPropertyChanging("File_name");
                _File_name = StructuralObject.SetValidValue(value, false, "File_name");
                ReportPropertyChanged("File_name");
                OnFile_nameChanged();
            }
        }
        private global::System.String _File_name;
        partial void OnFile_nameChanging(global::System.String value);
        partial void OnFile_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] File_content
        {
            get
            {
                return StructuralObject.GetValidValue(_File_content);
            }
            set
            {
                OnFile_contentChanging(value);
                ReportPropertyChanging("File_content");
                _File_content = StructuralObject.SetValidValue(value, false, "File_content");
                ReportPropertyChanged("File_content");
                OnFile_contentChanged();
            }
        }
        private global::System.Byte[] _File_content;
        partial void OnFile_contentChanging(global::System.Byte[] value);
        partial void OnFile_contentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> User_ID
        {
            get
            {
                return _User_ID;
            }
            set
            {
                OnUser_IDChanging(value);
                ReportPropertyChanging("User_ID");
                _User_ID = StructuralObject.SetValidValue(value, "User_ID");
                ReportPropertyChanged("User_ID");
                OnUser_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _User_ID;
        partial void OnUser_IDChanging(Nullable<global::System.Int32> value);
        partial void OnUser_IDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CookBookModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="user_name">Initial value of the User_name property.</param>
        /// <param name="email_id">Initial value of the Email_id property.</param>
        /// <param name="first_name">Initial value of the First_name property.</param>
        /// <param name="last_name">Initial value of the Last_name property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.String user_name, global::System.String email_id, global::System.String first_name, global::System.String last_name)
        {
            User user = new User();
            user.Id = id;
            user.User_name = user_name;
            user.Email_id = email_id;
            user.First_name = first_name;
            user.Last_name = last_name;
            return user;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User_name
        {
            get
            {
                return _User_name;
            }
            set
            {
                OnUser_nameChanging(value);
                ReportPropertyChanging("User_name");
                _User_name = StructuralObject.SetValidValue(value, false, "User_name");
                ReportPropertyChanged("User_name");
                OnUser_nameChanged();
            }
        }
        private global::System.String _User_name;
        partial void OnUser_nameChanging(global::System.String value);
        partial void OnUser_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email_id
        {
            get
            {
                return _Email_id;
            }
            set
            {
                OnEmail_idChanging(value);
                ReportPropertyChanging("Email_id");
                _Email_id = StructuralObject.SetValidValue(value, false, "Email_id");
                ReportPropertyChanged("Email_id");
                OnEmail_idChanged();
            }
        }
        private global::System.String _Email_id;
        partial void OnEmail_idChanging(global::System.String value);
        partial void OnEmail_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String First_name
        {
            get
            {
                return _First_name;
            }
            set
            {
                OnFirst_nameChanging(value);
                ReportPropertyChanging("First_name");
                _First_name = StructuralObject.SetValidValue(value, false, "First_name");
                ReportPropertyChanged("First_name");
                OnFirst_nameChanged();
            }
        }
        private global::System.String _First_name;
        partial void OnFirst_nameChanging(global::System.String value);
        partial void OnFirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Last_name
        {
            get
            {
                return _Last_name;
            }
            set
            {
                OnLast_nameChanging(value);
                ReportPropertyChanging("Last_name");
                _Last_name = StructuralObject.SetValidValue(value, false, "Last_name");
                ReportPropertyChanged("Last_name");
                OnLast_nameChanged();
            }
        }
        private global::System.String _Last_name;
        partial void OnLast_nameChanging(global::System.String value);
        partial void OnLast_nameChanged();

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CookBookModel", Name="GetUsers_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetUsers_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetUsers_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="user_name">Initial value of the User_name property.</param>
        /// <param name="email_id">Initial value of the Email_id property.</param>
        /// <param name="first_name">Initial value of the First_name property.</param>
        /// <param name="last_name">Initial value of the Last_name property.</param>
        public static GetUsers_Result CreateGetUsers_Result(global::System.Int32 id, global::System.String user_name, global::System.String email_id, global::System.String first_name, global::System.String last_name)
        {
            GetUsers_Result getUsers_Result = new GetUsers_Result();
            getUsers_Result.Id = id;
            getUsers_Result.User_name = user_name;
            getUsers_Result.Email_id = email_id;
            getUsers_Result.First_name = first_name;
            getUsers_Result.Last_name = last_name;
            return getUsers_Result;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value, "Id");
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User_name
        {
            get
            {
                return _User_name;
            }
            set
            {
                OnUser_nameChanging(value);
                ReportPropertyChanging("User_name");
                _User_name = StructuralObject.SetValidValue(value, false, "User_name");
                ReportPropertyChanged("User_name");
                OnUser_nameChanged();
            }
        }
        private global::System.String _User_name;
        partial void OnUser_nameChanging(global::System.String value);
        partial void OnUser_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email_id
        {
            get
            {
                return _Email_id;
            }
            set
            {
                OnEmail_idChanging(value);
                ReportPropertyChanging("Email_id");
                _Email_id = StructuralObject.SetValidValue(value, false, "Email_id");
                ReportPropertyChanged("Email_id");
                OnEmail_idChanged();
            }
        }
        private global::System.String _Email_id;
        partial void OnEmail_idChanging(global::System.String value);
        partial void OnEmail_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String First_name
        {
            get
            {
                return _First_name;
            }
            set
            {
                OnFirst_nameChanging(value);
                ReportPropertyChanging("First_name");
                _First_name = StructuralObject.SetValidValue(value, false, "First_name");
                ReportPropertyChanged("First_name");
                OnFirst_nameChanged();
            }
        }
        private global::System.String _First_name;
        partial void OnFirst_nameChanging(global::System.String value);
        partial void OnFirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Last_name
        {
            get
            {
                return _Last_name;
            }
            set
            {
                OnLast_nameChanging(value);
                ReportPropertyChanging("Last_name");
                _Last_name = StructuralObject.SetValidValue(value, false, "Last_name");
                ReportPropertyChanged("Last_name");
                OnLast_nameChanged();
            }
        }
        private global::System.String _Last_name;
        partial void OnLast_nameChanging(global::System.String value);
        partial void OnLast_nameChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CookBookModel", Name="ReadFile_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ReadFile_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ReadFile_Result object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="file_name">Initial value of the File_name property.</param>
        /// <param name="file_content">Initial value of the File_content property.</param>
        public static ReadFile_Result CreateReadFile_Result(global::System.Byte id, global::System.String file_name, global::System.Byte[] file_content)
        {
            ReadFile_Result readFile_Result = new ReadFile_Result();
            readFile_Result.ID = id;
            readFile_Result.File_name = file_name;
            readFile_Result.File_content = file_content;
            return readFile_Result;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value, "ID");
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Byte _ID;
        partial void OnIDChanging(global::System.Byte value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String File_name
        {
            get
            {
                return _File_name;
            }
            set
            {
                OnFile_nameChanging(value);
                ReportPropertyChanging("File_name");
                _File_name = StructuralObject.SetValidValue(value, false, "File_name");
                ReportPropertyChanged("File_name");
                OnFile_nameChanged();
            }
        }
        private global::System.String _File_name;
        partial void OnFile_nameChanging(global::System.String value);
        partial void OnFile_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] File_content
        {
            get
            {
                return StructuralObject.GetValidValue(_File_content);
            }
            set
            {
                OnFile_contentChanging(value);
                ReportPropertyChanging("File_content");
                _File_content = StructuralObject.SetValidValue(value, false, "File_content");
                ReportPropertyChanged("File_content");
                OnFile_contentChanged();
            }
        }
        private global::System.Byte[] _File_content;
        partial void OnFile_contentChanging(global::System.Byte[] value);
        partial void OnFile_contentChanged();

        #endregion

    }

    #endregion

}
